Merge ICU421 to Android.
Bug: 1823720
Reviewed-by: jessewilson@google.com, enh@google.com
CC:
Signed-off-by:

diff --git a/Makefile.in b/Makefile.in
--- a/Makefile.in
+++ b/Makefile.in
@@ -1,6 +1,6 @@
 #******************************************************************************
 #
-#   Copyright (C) 1998-2007, International Business Machines
+#   Copyright (C) 1998-2009, International Business Machines
 #   Corporation and others.  All Rights Reserved.
 #
 #******************************************************************************
@@ -32,15 +32,16 @@ subdir = .
 @SAMPLES_TRUE@SAMPLE = samples
 
 DOXYGEN = @DOXYGEN@
+DOCZIP = icu-docs.zip
 
 ## Files to remove for 'make clean'
-CLEANFILES = *~ 
+CLEANFILES = *~
 
 ## Files built (autoconfed) and installed
-INSTALLED_BUILT_FILES = $(top_builddir)/config/Makefile.inc $(top_builddir)/config/icu-config @platform_make_fragment@ $(EXTRA_DATA:%=$(DESTDIR)$(pkglibdir)/%)
+INSTALLED_BUILT_FILES = $(top_builddir)/config/Makefile.inc $(top_builddir)/config/pkgdata.inc $(top_builddir)/config/icu-config @platform_make_fragment@ $(EXTRA_DATA:%=$(DESTDIR)$(pkglibdir)/%)
 
 ## Files built (autoconfed) but not installed
-LOCAL_BUILT_FILES = icudefs.mk
+LOCAL_BUILT_FILES = icudefs.mk config/icucross.mk
 
 DOCDIRS = common i18n
 SUBDIRS =  stubdata common i18n $(LAYOUT) tools data $(ICUIO) $(EXTRA) $(SAMPLE) $(TEST)
@@ -70,7 +71,7 @@ install: install-recursive install-local
 clean: clean-recursive-with-twist clean-local
 distclean : distclean-recursive distclean-local
 dist: dist-recursive dist-local
-check: all check-recursive check-local
+check: all check-recursive
 check-recursive: all
 
 ifeq ($(DOXYGEN),)
@@ -85,6 +86,10 @@ doc/html/index.html: Doxyfile $(wildcard ./common/unicode/platform.h $(srcdir)/c
 
 Doxyfile: $(srcdir)/Doxyfile.in
 	CONFIG_FILES=$@ CONFIG_HEADERS= $(SHELL) ./config.status
+
+$(DOCZIP): doc
+	-$(RMV) $(DOCZIP)
+	( cd doc/html ; zip -r ../../$(DOCZIP) * )
 endif
 
 LOCAL_SUBDIRS = $(SUBDIRS)
@@ -129,9 +134,11 @@ install-icu: $(INSTALLED_BUILT_FILES)
 	$(INSTALL_DATA) $(top_srcdir)/../license.html $(DESTDIR)$(pkgdatadir)/license.html
 	$(INSTALL_SCRIPT) $(top_builddir)/config/icu-config $(DESTDIR)$(bindir)/icu-config
 	$(INSTALL_DATA) $(top_builddir)/config/Makefile.inc $(DESTDIR)$(pkglibdir)/Makefile.inc
+	$(INSTALL_DATA) $(top_builddir)/config/pkgdata.inc $(DESTDIR)$(pkglibdir)/pkgdata.inc
 	cd $(DESTDIR)$(pkglibdir)/..; \
 	    $(RM) current && ln -s $(VERSION) current; \
-	    $(RM) Makefile.inc && ln -s current/Makefile.inc Makefile.inc
+	    $(RM) Makefile.inc && ln -s current/Makefile.inc Makefile.inc; \
+	    $(RM) pkgdata.inc && ln -s current/pkgdata.inc pkgdata.inc
 
 ifeq ($(DOXYGEN),)
 install-doc:
@@ -153,14 +160,19 @@ dist-local:
 
 clean-local:
 	test -z "$(CLEANFILES)" || $(RMV) $(CLEANFILES)
-	$(RMV) Doxyfile doc
+	$(RMV) Doxyfile doc $(DOCZIP)
 
 distclean-local: clean-local
-	$(RMV) $(top_builddir)/config/Makefile.inc $(top_builddir)/config/icu-config
-	$(RMV) config.cache config.log config.status
+	$(RMV) $(top_builddir)/config/Makefile.inc $(top_builddir)/config/pkgdata.inc $(top_builddir)/config/icu-config
+	$(RMV) config.cache config.log config.status $(top_builddir)/config/icucross.mk
 	$(RMV) Makefile config/Makefile icudefs.mk $(LIBDIR) $(BINDIR)
 
-check-local:
+check-local: $(top_builddir)/config/icu-config $(top_builddir)/config/Makefile.inc $(top_builddir)/config/pkgdata.inc
+	@echo verifying that icu-config --selfcheck can operate
+	@test "passed" = "$(shell $(top_builddir)/config/icu-config --selfcheck 2>&1)" || (echo "FAIL: icu-config could not run properly." ; exit 1)
+	@echo verifying that $(MAKE) -f Makefile.inc selfcheck can operate
+	@test "passed" = "$(shell $(MAKE) --no-print-directory -f $(top_builddir)/config/Makefile.inc SELFCHECK=1 selfcheck)" || (echo "FAIL: Makefile.inc could not run properly." ; exit 1 )
+	@echo "PASS: config selfcheck OK"
 
 #$(srcdir)/configure : $(srcdir)/configure.in $(top_srcdir)/aclocal.m4
 #	cd $(srcdir) && $(AUTOCONF)
@@ -169,11 +181,30 @@ icudefs.mk: $(srcdir)/icudefs.mk.in  $(top_builddir)/config.status
 	cd $(top_builddir) \
 		&& CONFIG_FILES=$(subdir)/$@ CONFIG_HEADERS= $(SHELL) ./config.status
 
+config/icucross.mk: $(top_builddir)/icudefs.mk  $(top_builddir)/Makefile
+	@echo rebuilding $@
+	@(echo "CROSS_ICU_VERSION=$(VERSION)" ;\
+	  echo "TOOLEXEEXT=$(EXEEXT)" \
+	   ) > $@
+	@(echo 'TOOLBINDIR=$$(cross_buildroot)/bin' ;\
+	  echo 'TOOLLIBDIR=$$(cross_buildroot)/lib' ;\
+	  echo "INVOKE=$(LDLIBRARYPATH_ENVVAR)=$(LIBRARY_PATH_PREFIX)"'$$(TOOLLIBDIR):$$(cross_buildroot)/stubdata:$$(cross_buildroot)/tools/ctestfw:$$$$'"$(LDLIBRARYPATH_ENVVAR)" ;\
+	  echo "PKGDATA_INVOKE=$(LDLIBRARYPATH_ENVVAR)=$(LIBRARY_PATH_PREFIX)"'$$(cross_buildroot)/stubdata:$$(cross_buildroot)/tools/ctestfw:$$(TOOLLIBDIR):$$$$'"$(LDLIBRARYPATH_ENVVAR) "'$$'"(PKGDATA_INVOKE_OPTS)" ;\
+	  echo ) >> $@
+
 Makefile: $(srcdir)/Makefile.in icudefs.mk $(top_builddir)/config.status
 	cd $(top_builddir) \
 		&& CONFIG_FILES=$(subdir)/$@ CONFIG_HEADERS= $(SHELL) ./config.status
 
 $(top_builddir)/config/Makefile.inc: $(srcdir)/config/Makefile.inc.in  $(top_builddir)/config.status
+	cd $(top_builddir) \
+		&& CONFIG_FILES=$@ CONFIG_HEADERS= $(SHELL) ./config.status
+
+$(top_builddir)/config/pkgdata.inc: icudefs.mk $(top_builddir)/config/pkgdataMakefile
+	cd $(top_builddir)/config; \
+		$(MAKE) -f pkgdataMakefile
+
+$(top_builddir)/config/pkgdataMakefile:
 	cd $(top_builddir) \
 		&& CONFIG_FILES=$@ CONFIG_HEADERS= $(SHELL) ./config.status
 
